x1 = int(input("Enter the value for x1: "))
x2 = int(input("Enter the value for x2: "))
y1 = int(input("Enter the value for y1: "))
y2 = int(input("Enter the value for y2: "))
print("\nx1 =",x1,"\nx2 =",x2,"\ny1 =",y1,"\ny2 =",y2)
distance = (((x2 - x1)*2 + (y2 - y1)2)*0.5)
print("\nThe distance of the given points: ",distance)
