name = input("Enter your name: ")
registernumber = input("Enter your register number: ")
eMail = input("Enter your E-mail: ")
phone = int(input("Enter your mobile number: "))
print("~~~~STUDENT DETAILS~~~~ ")
print("Name      :",name)
print("register num:",registernumber)
print("Email     :",eMail)
print("Contact no:",phone)
